export const addToHistoryConst = {
    ADD_TO_HISTORY_REQUEST : 'ADD_TO_HISTORY_REQUEST',  
    ADD_TO_HISTORY_SUCCESS : 'ADD_TO_HISTORY_SUCCESS',
    ADD_TO_HISTORY_FAIL : 'ADD_TO_HISTORY_FAIL',
};

export const getUseHistoryConst = {
    FETCH_HISTORY_REQUEST : 'FETCH_HISTORY_REQUEST',  
    FETCH_HISTORY_SUCCESS : 'FETCH_HISTORY_SUCCESS',
    FETCH_HISTORY_FAIL : 'FETCH_HISTORY_FAIL',
}; 
