export const createPlaylistConst = {
    CREATE_PLAYLIST_REQUEST : 'CREATE_PLAYLIST_REQUEST',  
    CREATE_PLAYLIST_SUCCESS : 'CREATE_PLAYLIST_SUCCESS',
    CREATE_PLAYLIST_FAIL : 'CREATE_PLAYLIST_FAIL',
};

export const addToPlaylistConst = {
    ADD_TO_PLAYLIST_REQUEST : 'ADD_TO_PLAYLIST_REQUEST',  
    ADD_TO_PLAYLIST_SUCCESS : 'ADD_TO_PLAYLIST_SUCCESS',
    ADD_TO_PLAYLIST_FAIL : 'ADD_TO_PLAYLIST_FAIL',
}; 

export const deletePlaylistConst = {
    DELETE_PLAYLIST_REQUEST : 'DELETE_PLAYLIST_REQUEST',  
    DELETE_PLAYLIST_SUCCESS : 'DELETE_PLAYLIST_SUCCESS',
    DELETE_PLAYLIST_FAIL : 'DELETE_PLAYLIST_FAIL',
}; 

export const deleteAllPlaylistConst = {
    DELETE_ALL_PLAYLIST_REQUEST : 'DELETE_ALL_PLAYLIST_REQUEST',  
    DELETE_ALL_PLAYLIST_SUCCESS : 'DELETE_ALL_PLAYLIST_SUCCESS',
    DELETE_ALL_PLAYLIST_FAIL : 'DELETE_ALL_PLAYLIST_FAIL',
}; 

export const fetchAllPlaylistConst = {
    FETCH_ALL_PLAYLIST_REQUEST : 'FETCH_ALL_PLAYLIST_REQUEST',  
    FETCH_ALL_PLAYLIST_SUCCESS : 'FETCH_ALL_PLAYLIST_SUCCESS',
    FETCH_ALL_PLAYLIST_FAIL : 'FETCH_ALL_PLAYLIST_FAIL',
}; 