export const createSongConst = {
    CREATE_SONG_REQUEST : 'CREATE_SONG_REQUEST',  
    CREATE_SONG_SUCCESS : 'CREATE_SONG_SUCCESS',
    CREATE_SONG_FAIL : 'CREATE_SONG_FAIL',
};

export const fetchAllSongConst = {
    FETCH_SONG_REQUEST : 'FETCH_SONGS_REQUEST',  
    FETCH_SONG_SUCCESS : 'FETCH_SONGS_SUCCESS',
    FETCH_SONG_FAIL : 'FETCH_SONGS_FAIL',
}; 

export const removeSongConst= {
    REMOVE_SONG_REQUEST : 'REMOVE_SONG_REQUEST',  
    REMOVE_SONG_SUCCESS : 'REMOVE_SONG_SUCCESS',
    REMOVE_SONG_FAIL : 'REMOVE_SONG_FAIL',
}; 

export const clearAllSongConst= {
    CLEAR_ALL_SONG_REQUEST : 'CLEAR_ALL_SONG_REQUEST',  
    CLEAR_ALL_SONG__SUCCESS : 'CLEAR_ALL_SONG__SUCCESS',
    CLEAR_ALL_SONG_FAIL : 'CLEAR_ALL_SONG_FAIL',
}; 

